import { Router } from 'express';
import authRoutes from './auth.routes';
import healthRoutes from './health.routes';
import marketRoutes from './market.routes';
import portfolioRoutes from './portfolio.routes';
import dividendRoutes from './dividend.routes';
import settingsRoutes from './settings.routes';
import insightsRoutes from './insights.routes';
import goalsRoutes from './goals.routes';
import intelligenceRoutes from './portfolioIntelligence.routes';
import leaderboardRoutes from './leaderboard.routes';
import usersRoutes from './users.routes';
import socialRoutes from './social.routes';
import transactionRoutes from './transaction.routes';
import alertRoutes from './alert.routes';
import priceAlertRoutes from './priceAlert.routes';
import analystRoutes from './analyst.routes';
import milestoneRoutes from './milestone.routes';
import fundamentalsRoutes from './fundamentals.routes';
import deepResearchRoutes from './deep-research.routes';
import nalaRoutes from './nala.routes';
import watchlistRoutes from './watchlist.routes';
import notificationsRoutes from './notifications.routes';
import plaidRoutes from './plaid.routes';
import billingRoutes from './billing.routes';
import stockFollowRoutes from './stock-follow.routes';
import creatorRoutes from './creator.routes';
import referralRoutes from './referral.routes';
import waitlistRoutes from './waitlist.routes';
import pushRoutes from './push.routes';
import appleIapRoutes from './apple-iap.routes';
import { config } from '../config';

const router = Router();

router.use('/auth', authRoutes);
router.use('/health', healthRoutes);
router.use('/market', marketRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/dividends', dividendRoutes);
router.use('/settings', settingsRoutes);
router.use('/insights', insightsRoutes);
router.use('/goals', goalsRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/users', usersRoutes);
router.use('/social', socialRoutes);
router.use('/transactions', transactionRoutes);
router.use('/alerts', alertRoutes);
router.use('/price-alerts', priceAlertRoutes);
router.use('/analyst', analystRoutes);
router.use('/milestones', milestoneRoutes);
router.use('/fundamentals', fundamentalsRoutes);
router.use('/nala/deep-research', deepResearchRoutes);
router.use('/nala', nalaRoutes);
router.use('/watchlists', watchlistRoutes);
router.use('/stock-follows', stockFollowRoutes);
router.use('/creator', creatorRoutes);
router.use('/referral', referralRoutes);
router.use('/waitlist', waitlistRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/push', pushRoutes);
router.use('/plaid', plaidRoutes);
if (config.billingEnabled) {
  router.use('/billing', billingRoutes);
}
router.use('/billing', appleIapRoutes);

export default router;
