import { Router } from 'express';
import authRoutes from './auth.routes';
import healthRoutes from './health.routes';
import marketRoutes from './market.routes';
import portfolioRoutes from './portfolio.routes';
import dividendRoutes from './dividend.routes';
import settingsRoutes from './settings.routes';
import insightsRoutes from './insights.routes';
import goalsRoutes from './goals.routes';
import intelligenceRoutes from './portfolioIntelligence.routes';
import leaderboardRoutes from './leaderboard.routes';
import usersRoutes from './users.routes';
import socialRoutes from './social.routes';
import transactionRoutes from './transaction.routes';
import alertRoutes from './alert.routes';
import priceAlertRoutes from './priceAlert.routes';
import analystRoutes from './analyst.routes';
import milestoneRoutes from './milestone.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/health', healthRoutes);
router.use('/market', marketRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/dividends', dividendRoutes);
router.use('/settings', settingsRoutes);
router.use('/insights', insightsRoutes);
router.use('/goals', goalsRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/users', usersRoutes);
router.use('/social', socialRoutes);
router.use('/transactions', transactionRoutes);
router.use('/alerts', alertRoutes);
router.use('/price-alerts', priceAlertRoutes);
router.use('/analyst', analystRoutes);
router.use('/milestones', milestoneRoutes);

export default router;
